### ISSUE TITLE
Pretrained VAE Models for SVHN

### ISSUE THREAD

**Issue by oliverweissl** [coinse/SINVAD#1]
Hello, are the VAE models available somewhere for reference? I saw the ones for MNIST and fashion MNIST in the other branch, but is there  the originals?

**Comment by ntrolls** [comment]
@oliverweissl Can I ask you to clarify what you mean by original VAE models...? For SINVAD, a VAE model needs to be trained against a specific dataset to learn the latent representation space of that dataset. It does not come pre-trained. Or am I missing something?

**Comment by ntrolls** [comment]
Ah, apparently I missed the "title" of this issue... you are asking for the VAE model trained with SVHN. We can check, but you may have to train one yourself...

@smkang96 Do we have one somewhere...?

**Comment by oliverweissl** [comment]
Yes sorry for the confusion, i saw in the notebooks you reference the state dicts of the trained VAEs (`./vae/models/MNIST_EnD.pth`). It would be great if those are available somehow. Thanks for the fast replies!!

**Comment by smkang96** [comment]
Hi Oliver, thanks for your interest in our work. My intention was for models to be trained from scratch (e.g. [#](https://github.com/coinse/SINVAD/blob/master/init_scripts/init_rq1.sh)) but sure I can provide the original models.

... apparently I can't upload `.pth` files on this issue, so I'll send the files to you via email.

**Comment by oliverweissl** [comment]
I understand, but i appreciate the option for sending the files, you can use this email:
weissl@fortiss.org

Thank you in advance!

**Comment by smkang96** [comment]
I actually found your email and sent you the files soon after I wrote that comment, at Dec 12 00:19 UTC, could you check your email and let me know if this was what you were looking for? Thanks.

**Comment by oliverweissl** [comment]
Ahh yes i saw it now, thank you very much! this helps a lot :)
